### ISSUE TITLE
Slow and laggin chrome when browsing

### ISSUE THREAD

**Issue by rasik33** [Magisk-Modules-Alt-Repo/Re-Malwack#1]
I experience very slow browsing when this is installed. Why is that?

**Comment by ZG089** [comment]
> I experience very slow browsing when this is installed. Why is that?

@rasik33 Maybe your device is a low-end one?
It's always recommended to use ad block modules like Re-Malwack in a mid-range or a high-end device. Since their hosts file are too big that the low-end devices can't go without lag in that point.

Soon we will release a light version of Re-Malwack. Stay tuned !

**Comment by ZG089** [comment]
@rasik33 
commits [18a5bfa](https://github.com/ZG089/Re-Malwack/commit/18a5bfaad9b52577d71783f4b4a4de0dc39b3892) - [e26a5f8](https://github.com/ZG089/Re-Malwack/commit/e26a5f8c3c776a26dcabc01769972b2144c7ad70) may fix this issue. Wait for v5.3.0 to drop.
